site_name: moduleprofiler
nav:
  - About: index.md
  - Documentation: documentation.md
  - Tutorial: tutorial.md
  - Reference:
    - Introduction: reference.md
    - "Modules":
      - modules/linear.md
      - modules/conv1d.md
      - modules/lstmcell.md
      - modules/grucell.md
      - modules/gru.md
  - License: license.md
copyright: |
  &copy; 2024 <a href="https://www.estebangomez.me" target="_blank">Esteban Gómez</a>
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      # custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            line_length: 79
  - autorefs
extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css
