site_name: moduleprofiler
nav:
  - Documentation: index.md
  - Tutorial: tutorial.md
  - Reference: reference.md
copyright: |
  &copy; <a href="https://www.estebangomez.me" target="_blank">Esteban Gómez</a> 2024
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime